<?php

/**
 * NextBridge - German localization
 *
 * @author Laurent Dinclaux <laurent@gecka.nc>
 * @copyright 2026 Gecka
 * @license AGPL-3.0-or-later
 */

$labels['save'] = 'Speichern';
$labels['cancel'] = 'Abbrechen';
$labels['saveto'] = 'In Nextcloud speichern...';
$labels['saveall'] = 'Alle in Nextcloud speichern';
$labels['fromcloud'] = 'Aus Nextcloud anhängen...';
$labels['attaching'] = 'Anfügen...';
$labels['sharelink'] = 'Freigabelink einfügen...';
$labels['linkinserted'] = 'Freigabelink eingefügt';
$labels['addtocalendar'] = 'Zu Nextcloud-Kalender hinzufügen';
$labels['eventadded'] = 'Ereignis zum Kalender hinzugefügt';
$labels['eventupdated'] = 'Ereignis im Kalender aktualisiert';
$labels['selectcalendar'] = 'Kalender auswählen:';
